### ISSUE TITLE
[Bug] Not playing livestream

### ISSUE THREAD

**Issue by Hiosdra** [edgafner/GBrowser#4] opened 2020-10-14 14:08 UTC
Hi, I've tried to watch livestream of [Kotlin 1.4 Online Event Day 3](https://www.youtube.com/watch?v=KObxmllDzPY), but browser said, that HTML5 is not supported. Is it possible to add support to it? If you cannot reproduce it, I can add some logs to issue. My IntelliJ version is 2020.2.3 (newest as of time). 

By the way, great work with this plugin 👍

**Comment by Jonatha1983** [comment] 2020-10-15 07:01
Hi @Hiosdra  I am currently busy with other projects so not sure I ll make it in the near future but feel free to contribute and fix  it.

**Comment by Jonatha1983** [comment] 2021-12-28 09:02
@Hiosdra Hi 

I was able to reproduce, however it will take me some more time to fix this. Since those are much low level staff I am use to deal with.

**Comment by Hiosdra** [comment] 2021-12-28 09:26
😍🥳❤️

**Comment by Jonatha1983** [comment] 2024-01-07 16:48
@Hiosdra, the upcoming release v2024.1.3 includes many new features, including authenticating with a Google account. I am closing this ticket as it is fixed in the forthcoming version.

**Closed by Jonatha1983** 2024-01-07 16:48 UTC
